DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS voltage;

CREATE TABLE temperature (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    reading DOUBLE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE voltage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    reading DOUBLE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);